all:
  hosts:
    srv1:
      ansible_host: "{{ CONFIGURABLE_HOST1 }}"
    # srv2:
    #   ansible_host: "{{ CONFIGURABLE_HOST2 }}"
  vars:
    ansible_user: "{{ USER_ANSIBLE_CONNECT }}"
    ansible_connection: ssh
    ansible_ssh_private_key_file: "{{ SSH_PRIVATE_KEY_PATH }}"
